# Generated by Django 5.1.2 on 2024-10-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_subscriptionprice_usersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(default=2, upload_to='subscriptions/'),
            preserve_default=False,
        ),
    ]
