# Generated by Django 5.1.3 on 2024-11-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('pro', 'Pro Membership'), ('geek', 'Pro Membership'), ('lunatic', 'Lunatic Membership')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['pro', 'geek', 'lunatic'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
