# Generated by Django 5.1.3 on 2024-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='color',
            field=models.CharField(blank=True, help_text='Color for membership', max_length=120, null=True),
        ),
    ]
