# Generated by Django 5.1.2 on 2024-10-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
