# Generated by Django 5.1.3 on 2024-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qualified',
            field=models.CharField(choices=[('important', 'Important'), ('guide', 'Guide')], default='important', max_length=20),
        ),
    ]
