# Generated by Django 5.1.3 on 2024-11-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_qualified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='qualified',
            new_name='classification',
        ),
    ]
