# Generated by Django 5.1.3 on 2024-11-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('money', models.IntegerField()),
                ('color', models.CharField(max_length=120)),
                ('level', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ranks/')),
            ],
        ),
    ]
