# Generated by Django 5.1.3 on 2024-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this rank active?'),
        ),
        migrations.AddField(
            model_name='rank',
            name='features',
            field=models.TextField(blank=True, help_text='Features for rank, seperated by new line', null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='color',
            field=models.CharField(blank=True, help_text='Color for rank', max_length=120),
        ),
        migrations.AlterField(
            model_name='rank',
            name='level',
            field=models.IntegerField(help_text='Level of rank', unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='money',
            field=models.IntegerField(blank=True, help_text='Cost to reach rank', null=True),
        ),
    ]
