# Generated by Django 5.1.3 on 2024-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rank_active_rank_features_alter_rank_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='color',
            field=models.CharField(blank=True, help_text='Color for rank', max_length=120, null=True),
        ),
    ]
